import type { EmitterPreset } from '../landmarks/records.ts';

/**
 * Effect presets (S4 W3-E): the static behaviour of every emitter kind the EffectsSystem realizes.
 * Lengths are km per unit of the emitter's `scale` (which already carries the landmark's design scale),
 * times are seconds of the effect clock (env.tFx / SceneState.tFx). Colours are linear albedo.
 *
 * Particle families (particles.ts):
 *  - plume  smoke, steam: a buoyant column that rises with a decaying velocity, widens, bends downwind
 *           and — under an ash deck — flattens and spreads under the ceiling (an umbrella that fades into
 *           the pall, so the plume merges into the deck with no plane intersection)
 *  - ash    broad, thin ash clouds drifting downwind under the deck from the plume (or from `at` to `to`:
 *           low sheets over a plain)
 *  - spray  the spray cloud at a waterfall's foot (generated by the falls, not declared)
 *  - mist / beam  static geometry (mist cards, the Morgul beam) — no particles
 *  - embers / sparks  additive points handed to the EmissionSystem (setDynamic): beacon flames, crater sparks
 */

/** The particle families of the billboard draw. */
export type PuffFamily = 'plume' | 'ash' | 'spray';

export interface PuffPreset {
  family: PuffFamily;
  /** puffs at rate 1, scale 1 (× rate × scale^COUNT_EXP, at quality density 1) */
  count: number;
  /** fewest puffs of a drawn emitter */
  minCount: number;
  /** seconds per puff life (× scale^LIFE_EXP: big plumes billow slowly) */
  life: number;
  /** free rise (km per scale; a deck ceiling caps it) */
  rise: number;
  /** column radius at the source and at the top of its free rise (km per scale) */
  r0: number;
  r1: number;
  /** umbrella (under a ceiling): its final radius as a multiple of r1, and its share of the life */
  spread: number;
  umbrella: number;
  /** downwind drift of the column top as a fraction of its rise, and of the umbrella (km per scale) */
  bend: number;
  drift: number;
  /** puff radius at birth and at the top (km per scale) */
  size0: number;
  size1: number;
  /** base opacity of one puff (the atlas density multiplies it) */
  opacity: number;
  /** linear albedo (the emitter's `color` overrides it) */
  albedo: [number, number, number];
  /** how much of the spill (lava / fires near the source) the puffs take: lit from below */
  spill: number;
  /** 0..1: the puffs dissolve as they rise (steam, chimney smoke) instead of keeping their density */
  dissolve: number;
  /** projected extent (px) below which the emitter is not drawn, and above which it gets all its puffs */
  lodPx: [number, number];
}

/** puff count ∝ scale^COUNT_EXP (a big plume gets more puffs, not only bigger ones) */
export const COUNT_EXP = 0.6;
/** puff life ∝ scale^LIFE_EXP */
export const LIFE_EXP = 0.3;

/**
 * The billboard presets. Doom's smoke (scale 3) is a ≈ 0.6 → 6 km wide column rising ≈ 15 km into the
 * deck with ≈ 96 puffs at density 1; Isengard's pits (1.5) are dark columns over the ring; a chimney
 * (≈ 0.04) is a thin wisp.
 */
export const PUFF: Record<'smoke' | 'ash' | 'steam' | 'spray', PuffPreset> = {
  smoke: {
    family: 'plume',
    count: 105,
    minCount: 6,
    life: 30,
    rise: 6,
    r0: 0.45,
    r1: 2.0,
    spread: 1.7,
    umbrella: 0.35,
    bend: 0.35,
    drift: 2.2,
    size0: 0.45,
    size1: 1.6,
    opacity: 0.42,
    albedo: [0.055, 0.052, 0.05],
    spill: 1,
    dissolve: 0.15,
    lodPx: [14, 90],
  },
  ash: {
    family: 'ash',
    count: 30,
    minCount: 4,
    life: 70,
    rise: 2.4,
    r0: 0.15,
    r1: 0.5,
    spread: 1,
    umbrella: 0,
    bend: 0,
    drift: 4.5,
    size0: 0.22,
    size1: 0.55,
    opacity: 0.32,
    albedo: [0.075, 0.071, 0.067],
    spill: 0.5,
    dissolve: 0,
    lodPx: [24, 120],
  },
  steam: {
    family: 'plume',
    count: 36,
    minCount: 5,
    life: 16,
    rise: 3.2,
    r0: 0.1,
    r1: 0.75,
    spread: 2,
    umbrella: 0.3,
    bend: 0.5,
    drift: 1.5,
    size0: 0.12,
    size1: 0.7,
    opacity: 0.5,
    albedo: [0.62, 0.62, 0.63],
    spill: 0.6,
    dissolve: 0.75,
    lodPx: [14, 90],
  },
  spray: {
    family: 'spray',
    count: 30,
    minCount: 4,
    life: 9,
    rise: 0.8,
    r0: 0.22,
    r1: 0.6,
    spread: 1,
    umbrella: 0,
    bend: 0.4,
    drift: 0,
    size0: 0.3,
    size1: 0.75,
    opacity: 0.6,
    albedo: [0.78, 0.8, 0.82],
    spill: 0.4,
    dissolve: 0.6,
    lodPx: [10, 80],
  },
};

/** Declared presets the billboard draw realizes (embers / sparks / mist / beam go elsewhere). */
export function isPuffPreset(p: EmitterPreset | 'spray'): p is 'smoke' | 'ash' | 'steam' | 'spray' {
  return p === 'smoke' || p === 'ash' || p === 'steam' || p === 'spray';
}

/** Every declared preset the EffectsSystem understands (the check flags anything else). */
export const KNOWN_PRESETS: readonly EmitterPreset[] = ['smoke', 'ash', 'embers', 'steam', 'mist', 'sparks', 'beam'];

/**
 * The plume / umbrella stays this far (km) under the deck height and its puffs fade out before they
 * reach it: the pall carries on where the plume stops (no plane intersection).
 */
export const DECK_MARGIN = 1.6;
/** deck cover (atmosphere.deckAt) above which an emitter has a ceiling */
export const DECK_CEILING_COVER = 0.3;

/** Sparks / embers (EmissionSystem dynamic lights): counts at rate 1, life, reach (km per scale). */
export const SPARKS = { count: 24, life: 2.6, rise: 0.9, spread: 0.6, radiusKm: 0.012, intensity: 3.2, lodPx: [40, 140] as [number, number] };
export const EMBERS = { flames: 5, sparks: 8, life: 1.6, rise: 0.22, radiusKm: 0.03, intensity: 4, lodPx: [3, 24] as [number, number] };

/** Mist cards: layers, the vertical spacing as a fraction of the half-width, grid resolution. */
export const MIST = { layers: 3, spacing: 0.06, maxSpacing: 0.18, grid: [16, 8] as [number, number], opacity: 0.55 };

/** The Morgul beam: core / glow half-widths (km per scale), HDR radiance, linear colour. */
export const BEAM = { core: 0.05, glow: 0.22, radiance: 14, color: [0.32, 1, 0.5] as [number, number, number], segments: 24 };

/**
 * Waterfalls: ribbon segments, the veil layer's width ratio, plunge-foam radius (× the fall's size) and its
 * rings / sectors, how far the curtain turns toward the camera around its axis (0 = flat on its path,
 * 1 = an axis billboard: a fall seen along its wall never collapses to a thread) and the draped falls'
 * visual widening.
 */
export const FALLS = { segments: 24, veil: 1.35, foam: 0.75, foamRings: 4, foamSectors: 24, facing: 0.45, drapeWiden: 1.4 };
